/**
 * Auto-generated file. Do not edit manually.
 * Generated by scripts/syncCollectionFloats.ts
 */

export interface CollectionFloatCatalogEntry {
  id: string;
  name: string;
  skins: Array<{
    id: string;
    name: string;
    minFloat: number;
    maxFloat: number;
  }>;
}

export const COLLECTIONS_WITH_FLOAT: CollectionFloatCatalogEntry[] = [
  {
    "id": "the-2021-dust-2-collection",
    "name": "The 2021 Dust 2 Collection",
    "skins": [
      {
        "id": "skin-58267df1cb9f",
        "name": "AK-47 | Gold Arabesque",
        "minFloat": 0,
        "maxFloat": 0.7
      }
    ]
  },
  {
    "id": "the-2021-mirage-collection",
    "name": "The 2021 Mirage Collection",
    "skins": [
      {
        "id": "skin-6c02d562ff70",
        "name": "AWP | Desert Hydra",
        "minFloat": 0,
        "maxFloat": 0.6
      }
    ]
  },
  {
    "id": "the-2021-train-collection",
    "name": "The 2021 Train Collection",
    "skins": [
      {
        "id": "skin-a841a452bb30",
        "name": "Glock-18 | Gamma Doppler",
        "minFloat": 0,
        "maxFloat": 0.5
      },
      {
        "id": "skin-95749d3887bc",
        "name": "M4A4 | The Coalition",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-2021-vertigo-collection",
    "name": "The 2021 Vertigo Collection",
    "skins": [
      {
        "id": "skin-5b5a4da33e83",
        "name": "M4A1-S | Imminent Danger",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-ancient-collection",
    "name": "The Ancient Collection",
    "skins": [
      {
        "id": "skin-f448735cd1c2",
        "name": "M4A1-S | Welcome to the Jungle",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-anubis-collection",
    "name": "The Anubis Collection",
    "skins": [
      {
        "id": "skin-bc3cce11bb11",
        "name": "M4A4 | Eye of Horus",
        "minFloat": 0,
        "maxFloat": 0.7
      }
    ]
  },
  {
    "id": "the-arms-deal-2-collection",
    "name": "The Arms Deal 2 Collection",
    "skins": [
      {
        "id": "skin-c1a20624eb22",
        "name": "SSG 08 | Blood in the Water",
        "minFloat": 0.06,
        "maxFloat": 0.2
      }
    ]
  },
  {
    "id": "the-arms-deal-3-collection",
    "name": "The Arms Deal 3 Collection",
    "skins": [
      {
        "id": "skin-5ca4267d0063",
        "name": "CZ75-Auto | Victoria",
        "minFloat": 0,
        "maxFloat": 0.75
      }
    ]
  },
  {
    "id": "the-arms-deal-collection",
    "name": "The Arms Deal Collection",
    "skins": [
      {
        "id": "skin-69390026d135",
        "name": "AWP | Lightning Strike",
        "minFloat": 0,
        "maxFloat": 0.08
      }
    ]
  },
  {
    "id": "the-bravo-collection",
    "name": "The Bravo Collection",
    "skins": [
      {
        "id": "skin-2599a8720f89",
        "name": "AK-47 | Fire Serpent",
        "minFloat": 0.06,
        "maxFloat": 0.76
      },
      {
        "id": "skin-706c54974c2f",
        "name": "Desert Eagle | Golden Koi",
        "minFloat": 0,
        "maxFloat": 0.12
      }
    ]
  },
  {
    "id": "the-breakout-collection",
    "name": "The Breakout Collection",
    "skins": [
      {
        "id": "skin-0ae3586c85da",
        "name": "M4A1-S | Cyrex",
        "minFloat": 0,
        "maxFloat": 0.5
      },
      {
        "id": "skin-c01d561550ed",
        "name": "P90 | Asiimov",
        "minFloat": 0,
        "maxFloat": 0.92
      }
    ]
  },
  {
    "id": "the-canals-collection",
    "name": "The Canals Collection",
    "skins": [
      {
        "id": "skin-549330dac6c0",
        "name": "AWP | The Prince",
        "minFloat": 0,
        "maxFloat": 0.6
      }
    ]
  },
  {
    "id": "the-chroma-2-collection",
    "name": "The Chroma 2 Collection",
    "skins": [
      {
        "id": "skin-7b1351c2adba",
        "name": "M4A1-S | Hyper Beast",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-bb6ba9602776",
        "name": "MAC-10 | Neon Rider",
        "minFloat": 0,
        "maxFloat": 0.45
      }
    ]
  },
  {
    "id": "the-chroma-3-collection",
    "name": "The Chroma 3 Collection",
    "skins": [
      {
        "id": "skin-815a9f1c0092",
        "name": "M4A1-S | Chantico's Fire",
        "minFloat": 0,
        "maxFloat": 0.99
      },
      {
        "id": "skin-8599a25e2c67",
        "name": "PP-Bizon | Judgement of Anubis",
        "minFloat": 0,
        "maxFloat": 0.5
      }
    ]
  },
  {
    "id": "the-chroma-collection",
    "name": "The Chroma Collection",
    "skins": [
      {
        "id": "skin-67b936c9cb52",
        "name": "AWP | Man-o'-war",
        "minFloat": 0.1,
        "maxFloat": 0.2
      },
      {
        "id": "skin-94878071c8d9",
        "name": "Galil AR | Chatterbox",
        "minFloat": 0.35,
        "maxFloat": 0.85
      }
    ]
  },
  {
    "id": "the-clutch-collection",
    "name": "The Clutch Collection",
    "skins": [
      {
        "id": "skin-e8144faeae9f",
        "name": "M4A4 | Neo-Noir",
        "minFloat": 0,
        "maxFloat": 0.9
      },
      {
        "id": "skin-d11a70424dd7",
        "name": "MP7 | Bloodsport",
        "minFloat": 0,
        "maxFloat": 0.65
      }
    ]
  },
  {
    "id": "the-cobblestone-collection",
    "name": "The Cobblestone Collection",
    "skins": [
      {
        "id": "skin-4f8d99d09ded",
        "name": "AWP | Dragon Lore",
        "minFloat": 0,
        "maxFloat": 0.7
      }
    ]
  },
  {
    "id": "the-control-collection",
    "name": "The Control Collection",
    "skins": [
      {
        "id": "skin-8fbcba8495ae",
        "name": "AWP | Fade",
        "minFloat": 0,
        "maxFloat": 0.08
      }
    ]
  },
  {
    "id": "the-cs20-collection",
    "name": "The CS20 Collection",
    "skins": [
      {
        "id": "skin-db4de1c248fa",
        "name": "AWP | Wildfire",
        "minFloat": 0.01,
        "maxFloat": 0.7
      },
      {
        "id": "skin-c70df63bf30b",
        "name": "FAMAS | Commemoration",
        "minFloat": 0,
        "maxFloat": 0.5
      }
    ]
  },
  {
    "id": "the-danger-zone-collection",
    "name": "The Danger Zone Collection",
    "skins": [
      {
        "id": "skin-09205674e246",
        "name": "AK-47 | Asiimov",
        "minFloat": 0.05,
        "maxFloat": 0.7
      },
      {
        "id": "skin-7b1ef066823d",
        "name": "AWP | Neo-Noir",
        "minFloat": 0,
        "maxFloat": 0.5
      }
    ]
  },
  {
    "id": "the-dreams-nightmares-collection",
    "name": "The Dreams & Nightmares Collection",
    "skins": [
      {
        "id": "skin-405f5570d1f6",
        "name": "AK-47 | Nightwish",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-feae180c4968",
        "name": "MP9 | Starlight Protector",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-esports-2013-collection",
    "name": "The eSports 2013 Collection",
    "skins": [
      {
        "id": "skin-b8631ce3380d",
        "name": "P90 | Death by Kitty",
        "minFloat": 0.08,
        "maxFloat": 0.32
      }
    ]
  },
  {
    "id": "the-esports-2013-winter-collection",
    "name": "The eSports 2013 Winter Collection",
    "skins": [
      {
        "id": "skin-ea15a4e5483d",
        "name": "M4A4 | X-Ray",
        "minFloat": 0,
        "maxFloat": 0.3
      }
    ]
  },
  {
    "id": "the-esports-2014-summer-collection",
    "name": "The eSports 2014 Summer Collection",
    "skins": [
      {
        "id": "skin-0827f8a09022",
        "name": "AK-47 | Jaguar",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-db764e1bb74b",
        "name": "M4A4 | Bullet Rain",
        "minFloat": 0.02,
        "maxFloat": 0.46
      }
    ]
  },
  {
    "id": "the-falchion-collection",
    "name": "The Falchion Collection",
    "skins": [
      {
        "id": "skin-0ffd6029f447",
        "name": "AK-47 | Aquamarine Revenge",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-f787cc672771",
        "name": "AWP | Hyper Beast",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-fever-collection",
    "name": "The Fever Collection",
    "skins": [
      {
        "id": "skin-5a39103af835",
        "name": "AWP | Printstream",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-f098f9b83e8b",
        "name": "FAMAS | Bad Trip",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-fracture-collection",
    "name": "The Fracture Collection",
    "skins": [
      {
        "id": "skin-dfd42a079f44",
        "name": "AK-47 | Legion of Anubis",
        "minFloat": 0,
        "maxFloat": 0.7
      },
      {
        "id": "skin-32a30647e564",
        "name": "Desert Eagle | Printstream",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-gallery-collection",
    "name": "The Gallery Collection",
    "skins": [
      {
        "id": "skin-5bd16f2599cf",
        "name": "Glock-18 | Gold Toof",
        "minFloat": 0,
        "maxFloat": 0.730496
      },
      {
        "id": "skin-aa9558c8a01f",
        "name": "M4A1-S | Vaporwave",
        "minFloat": 0,
        "maxFloat": 0.597321
      }
    ]
  },
  {
    "id": "the-gamma-2-collection",
    "name": "The Gamma 2 Collection",
    "skins": [
      {
        "id": "skin-1a5e885d9d28",
        "name": "AK-47 | Neon Revolution",
        "minFloat": 0,
        "maxFloat": 0.8
      },
      {
        "id": "skin-0305a5aaa4eb",
        "name": "FAMAS | Roll Cage",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-gamma-collection",
    "name": "The Gamma Collection",
    "skins": [
      {
        "id": "skin-73cc8d5fcd85",
        "name": "Glock-18 | Wasteland Rebel",
        "minFloat": 0,
        "maxFloat": 0.54
      },
      {
        "id": "skin-102a47219b11",
        "name": "M4A1-S | Mecha Industries",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-genesis-collection",
    "name": "The Genesis Collection",
    "skins": [
      {
        "id": "skin-4608abab8351",
        "name": "AK-47 | The Oligarch",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-e7c2a01982dd",
        "name": "M4A4 | Full Throttle",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-glove-collection",
    "name": "The Glove Collection",
    "skins": [
      {
        "id": "skin-01d7c60eddbb",
        "name": "M4A4 | Buzz Kill",
        "minFloat": 0,
        "maxFloat": 0.7
      },
      {
        "id": "skin-318f343e125d",
        "name": "SSG 08 | Dragonfire",
        "minFloat": 0,
        "maxFloat": 0.5
      }
    ]
  },
  {
    "id": "the-gods-and-monsters-collection",
    "name": "The Gods and Monsters Collection",
    "skins": [
      {
        "id": "skin-8af685c49feb",
        "name": "AWP | Medusa",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-graphic-design-collection",
    "name": "The Graphic Design Collection",
    "skins": [
      {
        "id": "skin-1c7cbe2db8f1",
        "name": "AWP | CMYK",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-havoc-collection",
    "name": "The Havoc Collection",
    "skins": [
      {
        "id": "skin-354b68a4149b",
        "name": "AK-47 | X-Ray",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-horizon-collection",
    "name": "The Horizon Collection",
    "skins": [
      {
        "id": "skin-74e670c4b279",
        "name": "AK-47 | Neon Rider",
        "minFloat": 0,
        "maxFloat": 0.8
      },
      {
        "id": "skin-87ee5eacc505",
        "name": "Desert Eagle | Code Red",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-huntsman-collection",
    "name": "The Huntsman Collection",
    "skins": [
      {
        "id": "skin-b14c9f234bc5",
        "name": "AK-47 | Vulcan",
        "minFloat": 0,
        "maxFloat": 0.9
      },
      {
        "id": "skin-e3516262b49a",
        "name": "M4A4 | Desert-Strike",
        "minFloat": 0,
        "maxFloat": 0.7
      }
    ]
  },
  {
    "id": "the-kilowatt-collection",
    "name": "The Kilowatt Collection",
    "skins": [
      {
        "id": "skin-82dc98e09ba6",
        "name": "AK-47 | Inheritance",
        "minFloat": 0,
        "maxFloat": 0.797346
      },
      {
        "id": "skin-b986a2456e28",
        "name": "AWP | Chrome Cannon",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-norse-collection",
    "name": "The Norse Collection",
    "skins": [
      {
        "id": "skin-2b99573c887b",
        "name": "AWP | Gungnir",
        "minFloat": 0,
        "maxFloat": 0.6
      }
    ]
  },
  {
    "id": "the-operation-broken-fang-collection",
    "name": "The Operation Broken Fang Collection",
    "skins": [
      {
        "id": "skin-7127818b09a6",
        "name": "Glock-18 | Neo-Noir",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-8e45a15cf7f5",
        "name": "M4A1-S | Printstream",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-operation-hydra-collection",
    "name": "The Operation Hydra Collection",
    "skins": [
      {
        "id": "skin-cfaaa2fab447",
        "name": "AWP | Oni Taiji",
        "minFloat": 0,
        "maxFloat": 0.5
      },
      {
        "id": "skin-06e2ad662c73",
        "name": "Five-SeveN | Hyper Beast",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-operation-riptide-collection",
    "name": "The Operation Riptide Collection",
    "skins": [
      {
        "id": "skin-96efe50cceb6",
        "name": "AK-47 | Leet Museo",
        "minFloat": 0,
        "maxFloat": 0.65
      },
      {
        "id": "skin-55623b84dd72",
        "name": "Desert Eagle | Ocean Drive",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-overpass-2024-collection",
    "name": "The Overpass 2024 Collection",
    "skins": [
      {
        "id": "skin-16430ed7568b",
        "name": "AK-47 | B the Monster",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-phoenix-collection",
    "name": "The Phoenix Collection",
    "skins": [
      {
        "id": "skin-370dfd3911e0",
        "name": "AUG | Chameleon",
        "minFloat": 0,
        "maxFloat": 0.5
      },
      {
        "id": "skin-bb633c21fc25",
        "name": "AWP | Asiimov",
        "minFloat": 0.18,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-prisma-2-collection",
    "name": "The Prisma 2 Collection",
    "skins": [
      {
        "id": "skin-3596d60709cc",
        "name": "Glock-18 | Bullet Queen",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-4dd5dccd2fdd",
        "name": "M4A1-S | Player Two",
        "minFloat": 0,
        "maxFloat": 0.84
      }
    ]
  },
  {
    "id": "the-prisma-collection",
    "name": "The Prisma Collection",
    "skins": [
      {
        "id": "skin-f971772d4996",
        "name": "Five-SeveN | Angry Mob",
        "minFloat": 0,
        "maxFloat": 0.7
      },
      {
        "id": "skin-8c5b9b7ce9f2",
        "name": "M4A4 | The Emperor",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-recoil-collection",
    "name": "The Recoil Collection",
    "skins": [
      {
        "id": "skin-3a4cc2c7a86f",
        "name": "AWP | Chromatic Aberration",
        "minFloat": 0,
        "maxFloat": 0.7
      },
      {
        "id": "skin-be37abed2b4d",
        "name": "USP-S | Printstream",
        "minFloat": 0,
        "maxFloat": 0.85
      }
    ]
  },
  {
    "id": "the-revolution-collection",
    "name": "The Revolution Collection",
    "skins": [
      {
        "id": "skin-1f95db2031e4",
        "name": "AK-47 | Head Shot",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-1aba3ea9ecc5",
        "name": "M4A4 | Temukau",
        "minFloat": 0,
        "maxFloat": 0.8
      }
    ]
  },
  {
    "id": "the-revolver-case-collection",
    "name": "The Revolver Case Collection",
    "skins": [
      {
        "id": "skin-4c83a4940ef3",
        "name": "M4A4 | Royal Paladin",
        "minFloat": 0,
        "maxFloat": 0.8
      },
      {
        "id": "skin-3d5660b8b090",
        "name": "R8 Revolver | Fade",
        "minFloat": 0,
        "maxFloat": 0.4
      }
    ]
  },
  {
    "id": "the-rising-sun-collection",
    "name": "The Rising Sun Collection",
    "skins": [
      {
        "id": "skin-6f4ba747e1a4",
        "name": "AUG | Akihabara Accept",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-shadow-collection",
    "name": "The Shadow Collection",
    "skins": [
      {
        "id": "skin-02db706d8db0",
        "name": "M4A1-S | Golden Coil",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-cf4c11689014",
        "name": "USP-S | Kill Confirmed",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-shattered-web-collection",
    "name": "The Shattered Web Collection",
    "skins": [
      {
        "id": "skin-f8cd1aa7fa55",
        "name": "AWP | Containment Breach",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-46bae9d6c6b0",
        "name": "MAC-10 | Stalker",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-snakebite-collection",
    "name": "The Snakebite Collection",
    "skins": [
      {
        "id": "skin-c62d08aa8da1",
        "name": "M4A4 | In Living Color",
        "minFloat": 0,
        "maxFloat": 0.79
      },
      {
        "id": "skin-7dc4b0b65850",
        "name": "USP-S | The Traitor",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-spectrum-2-collection",
    "name": "The Spectrum 2 Collection",
    "skins": [
      {
        "id": "skin-1b3ca668024e",
        "name": "AK-47 | The Empress",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-491a70af3255",
        "name": "P250 | See Ya Later",
        "minFloat": 0,
        "maxFloat": 0.7
      }
    ]
  },
  {
    "id": "the-spectrum-collection",
    "name": "The Spectrum Collection",
    "skins": [
      {
        "id": "skin-ba052cf18c66",
        "name": "AK-47 | Bloodsport",
        "minFloat": 0,
        "maxFloat": 0.45
      },
      {
        "id": "skin-0770dabcd885",
        "name": "USP-S | Neo-Noir",
        "minFloat": 0,
        "maxFloat": 0.7
      }
    ]
  },
  {
    "id": "the-sport-field-collection",
    "name": "The Sport & Field Collection",
    "skins": [
      {
        "id": "skin-81eee26a1c31",
        "name": "M4A1-S | Fade",
        "minFloat": 0,
        "maxFloat": 0.08
      }
    ]
  },
  {
    "id": "the-st-marc-collection",
    "name": "The St. Marc Collection",
    "skins": [
      {
        "id": "skin-921a5a81c48a",
        "name": "AK-47 | Wild Lotus",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-train-2025-collection",
    "name": "The Train 2025 Collection",
    "skins": [
      {
        "id": "skin-42c6a7e245d3",
        "name": "AWP | LongDog",
        "minFloat": 0,
        "maxFloat": 1
      }
    ]
  },
  {
    "id": "the-vanguard-collection",
    "name": "The Vanguard Collection",
    "skins": [
      {
        "id": "skin-ee1ab67b6434",
        "name": "AK-47 | Wasteland Rebel",
        "minFloat": 0.05,
        "maxFloat": 0.7
      },
      {
        "id": "skin-be569f85ce42",
        "name": "P2000 | Fire Elemental",
        "minFloat": 0,
        "maxFloat": 0.6
      }
    ]
  },
  {
    "id": "the-wildfire-collection",
    "name": "The Wildfire Collection",
    "skins": [
      {
        "id": "skin-8f7564b8b3eb",
        "name": "AK-47 | Fuel Injector",
        "minFloat": 0,
        "maxFloat": 1
      },
      {
        "id": "skin-62c54d49e07a",
        "name": "M4A4 | The Battlestar",
        "minFloat": 0,
        "maxFloat": 0.64
      }
    ]
  },
  {
    "id": "the-winter-offensive-collection",
    "name": "The Winter Offensive Collection",
    "skins": [
      {
        "id": "skin-31a3a09d007d",
        "name": "M4A4 | Asiimov",
        "minFloat": 0.18,
        "maxFloat": 1
      },
      {
        "id": "skin-eeeab72c939a",
        "name": "Sawed-Off | The Kraken",
        "minFloat": 0,
        "maxFloat": 0.4
      }
    ]
  }
];

export const COLLECTIONS_WITH_FLOAT_MAP: Record<string, CollectionFloatCatalogEntry> = Object.fromEntries(
  COLLECTIONS_WITH_FLOAT.map((collection) => [collection.id, collection]),
);

export const COLLECTIONS_WITH_FLOAT_BY_NAME: Record<string, CollectionFloatCatalogEntry> = Object.fromEntries(
  COLLECTIONS_WITH_FLOAT.map((collection) => [collection.name, collection]),
);

export interface CovertFloatEntry {
  collectionId: string;
  collectionName: string;
  minFloat: number;
  maxFloat: number;
}

export const COVERT_FLOAT_BY_BASENAME: Record<string, CovertFloatEntry> = Object.fromEntries(
  COLLECTIONS_WITH_FLOAT.flatMap((collection) =>
    collection.skins.map((skin) => [
      skin.name,
      {
        collectionId: collection.id,
        collectionName: collection.name,
        minFloat: skin.minFloat,
        maxFloat: skin.maxFloat,
      },
    ]),
  ),
);
