/**
 * This file is auto-generated by scripts/syncCollectionFloats.ts.
 * Last updated: 2025-09-23T16:52:19.018Z
 * Source: https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en/skins.json
 */
export interface CovertFloatRange {
  /** Базовое название скина без указания износа. */
  baseName: string;
  /** Минимальное возможное значение float для данного скина. */
  minFloat: number;
  /** Максимальное возможное значение float для данного скина. */
  maxFloat: number;
}

export interface CollectionFloatCatalogEntry {
  /** Удобный идентификатор коллекции (kebab-case). */
  id: string;
  /** Человекочитаемое название коллекции. */
  name: string;
  /** Список Covert-предметов и их диапазонов float. */
  covert: CovertFloatRange[];
}

export const COLLECTIONS_WITH_FLOAT: CollectionFloatCatalogEntry[] = [
  {
    id: "the-2021-dust-2-collection",
    name: "The 2021 Dust 2 Collection",
    covert: [
      {
        baseName: "AK-47 | Gold Arabesque",
        minFloat: 0,
        maxFloat: 0.7,
      },
    ],
  },
  {
    id: "the-2021-mirage-collection",
    name: "The 2021 Mirage Collection",
    covert: [
      {
        baseName: "AWP | Desert Hydra",
        minFloat: 0,
        maxFloat: 0.6,
      },
    ],
  },
  {
    id: "the-2021-train-collection",
    name: "The 2021 Train Collection",
    covert: [
      {
        baseName: "Glock-18 | Gamma Doppler",
        minFloat: 0,
        maxFloat: 0.5,
      },
      {
        baseName: "M4A4 | The Coalition",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-2021-vertigo-collection",
    name: "The 2021 Vertigo Collection",
    covert: [
      {
        baseName: "M4A1-S | Imminent Danger",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-ancient-collection",
    name: "The Ancient Collection",
    covert: [
      {
        baseName: "M4A1-S | Welcome to the Jungle",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-anubis-collection",
    name: "The Anubis Collection",
    covert: [
      {
        baseName: "M4A4 | Eye of Horus",
        minFloat: 0,
        maxFloat: 0.7,
      },
    ],
  },
  {
    id: "the-arms-deal-2-collection",
    name: "The Arms Deal 2 Collection",
    covert: [
      {
        baseName: "SSG 08 | Blood in the Water",
        minFloat: 0.06,
        maxFloat: 0.2,
      },
    ],
  },
  {
    id: "the-arms-deal-3-collection",
    name: "The Arms Deal 3 Collection",
    covert: [
      {
        baseName: "CZ75-Auto | Victoria",
        minFloat: 0,
        maxFloat: 0.75,
      },
    ],
  },
  {
    id: "the-arms-deal-collection",
    name: "The Arms Deal Collection",
    covert: [
      {
        baseName: "AWP | Lightning Strike",
        minFloat: 0,
        maxFloat: 0.08,
      },
    ],
  },
  {
    id: "the-bravo-collection",
    name: "The Bravo Collection",
    covert: [
      {
        baseName: "AK-47 | Fire Serpent",
        minFloat: 0.06,
        maxFloat: 0.76,
      },
      {
        baseName: "Desert Eagle | Golden Koi",
        minFloat: 0,
        maxFloat: 0.12,
      },
    ],
  },
  {
    id: "the-breakout-collection",
    name: "The Breakout Collection",
    covert: [
      {
        baseName: "M4A1-S | Cyrex",
        minFloat: 0,
        maxFloat: 0.5,
      },
      {
        baseName: "P90 | Asiimov",
        minFloat: 0,
        maxFloat: 0.92,
      },
    ],
  },
  {
    id: "the-canals-collection",
    name: "The Canals Collection",
    covert: [
      {
        baseName: "AWP | The Prince",
        minFloat: 0,
        maxFloat: 0.6,
      },
    ],
  },
  {
    id: "the-chroma-2-collection",
    name: "The Chroma 2 Collection",
    covert: [
      {
        baseName: "M4A1-S | Hyper Beast",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "MAC-10 | Neon Rider",
        minFloat: 0,
        maxFloat: 0.45,
      },
    ],
  },
  {
    id: "the-chroma-3-collection",
    name: "The Chroma 3 Collection",
    covert: [
      {
        baseName: "M4A1-S | Chantico's Fire",
        minFloat: 0,
        maxFloat: 0.99,
      },
      {
        baseName: "PP-Bizon | Judgement of Anubis",
        minFloat: 0,
        maxFloat: 0.5,
      },
    ],
  },
  {
    id: "the-chroma-collection",
    name: "The Chroma Collection",
    covert: [
      {
        baseName: "AWP | Man-o'-war",
        minFloat: 0.1,
        maxFloat: 0.2,
      },
      {
        baseName: "Galil AR | Chatterbox",
        minFloat: 0.35,
        maxFloat: 0.85,
      },
    ],
  },
  {
    id: "the-clutch-collection",
    name: "The Clutch Collection",
    covert: [
      {
        baseName: "M4A4 | Neo-Noir",
        minFloat: 0,
        maxFloat: 0.9,
      },
      {
        baseName: "MP7 | Bloodsport",
        minFloat: 0,
        maxFloat: 0.65,
      },
    ],
  },
  {
    id: "the-cobblestone-collection",
    name: "The Cobblestone Collection",
    covert: [
      {
        baseName: "AWP | Dragon Lore",
        minFloat: 0,
        maxFloat: 0.7,
      },
    ],
  },
  {
    id: "the-control-collection",
    name: "The Control Collection",
    covert: [
      {
        baseName: "AWP | Fade",
        minFloat: 0,
        maxFloat: 0.08,
      },
    ],
  },
  {
    id: "the-cs20-collection",
    name: "The CS20 Collection",
    covert: [
      {
        baseName: "AWP | Wildfire",
        minFloat: 0.01,
        maxFloat: 0.7,
      },
      {
        baseName: "FAMAS | Commemoration",
        minFloat: 0,
        maxFloat: 0.5,
      },
    ],
  },
  {
    id: "the-danger-zone-collection",
    name: "The Danger Zone Collection",
    covert: [
      {
        baseName: "AK-47 | Asiimov",
        minFloat: 0.05,
        maxFloat: 0.7,
      },
      {
        baseName: "AWP | Neo-Noir",
        minFloat: 0,
        maxFloat: 0.5,
      },
    ],
  },
  {
    id: "the-dreams-nightmares-collection",
    name: "The Dreams & Nightmares Collection",
    covert: [
      {
        baseName: "AK-47 | Nightwish",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "MP9 | Starlight Protector",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-esports-2013-collection",
    name: "The eSports 2013 Collection",
    covert: [
      {
        baseName: "P90 | Death by Kitty",
        minFloat: 0.08,
        maxFloat: 0.32,
      },
    ],
  },
  {
    id: "the-esports-2013-winter-collection",
    name: "The eSports 2013 Winter Collection",
    covert: [
      {
        baseName: "M4A4 | X-Ray",
        minFloat: 0,
        maxFloat: 0.3,
      },
    ],
  },
  {
    id: "the-esports-2014-summer-collection",
    name: "The eSports 2014 Summer Collection",
    covert: [
      {
        baseName: "AK-47 | Jaguar",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "M4A4 | Bullet Rain",
        minFloat: 0.02,
        maxFloat: 0.46,
      },
    ],
  },
  {
    id: "the-falchion-collection",
    name: "The Falchion Collection",
    covert: [
      {
        baseName: "AK-47 | Aquamarine Revenge",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "AWP | Hyper Beast",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-fever-collection",
    name: "The Fever Collection",
    covert: [
      {
        baseName: "AWP | Printstream",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "FAMAS | Bad Trip",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-fracture-collection",
    name: "The Fracture Collection",
    covert: [
      {
        baseName: "AK-47 | Legion of Anubis",
        minFloat: 0,
        maxFloat: 0.7,
      },
      {
        baseName: "Desert Eagle | Printstream",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-gallery-collection",
    name: "The Gallery Collection",
    covert: [
      {
        baseName: "Glock-18 | Gold Toof",
        minFloat: 0,
        maxFloat: 0.730496,
      },
      {
        baseName: "M4A1-S | Vaporwave",
        minFloat: 0,
        maxFloat: 0.597321,
      },
    ],
  },
  {
    id: "the-gamma-2-collection",
    name: "The Gamma 2 Collection",
    covert: [
      {
        baseName: "AK-47 | Neon Revolution",
        minFloat: 0,
        maxFloat: 0.8,
      },
      {
        baseName: "FAMAS | Roll Cage",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-gamma-collection",
    name: "The Gamma Collection",
    covert: [
      {
        baseName: "Glock-18 | Wasteland Rebel",
        minFloat: 0,
        maxFloat: 0.54,
      },
      {
        baseName: "M4A1-S | Mecha Industries",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-genesis-collection",
    name: "The Genesis Collection",
    covert: [
      {
        baseName: "AK-47 | The Oligarch",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "M4A4 | Full Throttle",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-glove-collection",
    name: "The Glove Collection",
    covert: [
      {
        baseName: "M4A4 | Buzz Kill",
        minFloat: 0,
        maxFloat: 0.7,
      },
      {
        baseName: "SSG 08 | Dragonfire",
        minFloat: 0,
        maxFloat: 0.5,
      },
    ],
  },
  {
    id: "the-gods-and-monsters-collection",
    name: "The Gods and Monsters Collection",
    covert: [
      {
        baseName: "AWP | Medusa",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-graphic-design-collection",
    name: "The Graphic Design Collection",
    covert: [
      {
        baseName: "AWP | CMYK",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-havoc-collection",
    name: "The Havoc Collection",
    covert: [
      {
        baseName: "AK-47 | X-Ray",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-horizon-collection",
    name: "The Horizon Collection",
    covert: [
      {
        baseName: "AK-47 | Neon Rider",
        minFloat: 0,
        maxFloat: 0.8,
      },
      {
        baseName: "Desert Eagle | Code Red",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-huntsman-collection",
    name: "The Huntsman Collection",
    covert: [
      {
        baseName: "AK-47 | Vulcan",
        minFloat: 0,
        maxFloat: 0.9,
      },
      {
        baseName: "M4A4 | Desert-Strike",
        minFloat: 0,
        maxFloat: 0.7,
      },
    ],
  },
  {
    id: "the-kilowatt-collection",
    name: "The Kilowatt Collection",
    covert: [
      {
        baseName: "AK-47 | Inheritance",
        minFloat: 0,
        maxFloat: 0.797346,
      },
      {
        baseName: "AWP | Chrome Cannon",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-norse-collection",
    name: "The Norse Collection",
    covert: [
      {
        baseName: "AWP | Gungnir",
        minFloat: 0,
        maxFloat: 0.6,
      },
    ],
  },
  {
    id: "the-operation-broken-fang-collection",
    name: "The Operation Broken Fang Collection",
    covert: [
      {
        baseName: "Glock-18 | Neo-Noir",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "M4A1-S | Printstream",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-operation-hydra-collection",
    name: "The Operation Hydra Collection",
    covert: [
      {
        baseName: "AWP | Oni Taiji",
        minFloat: 0,
        maxFloat: 0.5,
      },
      {
        baseName: "Five-SeveN | Hyper Beast",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-operation-riptide-collection",
    name: "The Operation Riptide Collection",
    covert: [
      {
        baseName: "AK-47 | Leet Museo",
        minFloat: 0,
        maxFloat: 0.65,
      },
      {
        baseName: "Desert Eagle | Ocean Drive",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-overpass-2024-collection",
    name: "The Overpass 2024 Collection",
    covert: [
      {
        baseName: "AK-47 | B the Monster",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-phoenix-collection",
    name: "The Phoenix Collection",
    covert: [
      {
        baseName: "AUG | Chameleon",
        minFloat: 0,
        maxFloat: 0.5,
      },
      {
        baseName: "AWP | Asiimov",
        minFloat: 0.18,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-prisma-2-collection",
    name: "The Prisma 2 Collection",
    covert: [
      {
        baseName: "Glock-18 | Bullet Queen",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "M4A1-S | Player Two",
        minFloat: 0,
        maxFloat: 0.84,
      },
    ],
  },
  {
    id: "the-prisma-collection",
    name: "The Prisma Collection",
    covert: [
      {
        baseName: "Five-SeveN | Angry Mob",
        minFloat: 0,
        maxFloat: 0.7,
      },
      {
        baseName: "M4A4 | The Emperor",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-recoil-collection",
    name: "The Recoil Collection",
    covert: [
      {
        baseName: "AWP | Chromatic Aberration",
        minFloat: 0,
        maxFloat: 0.7,
      },
      {
        baseName: "USP-S | Printstream",
        minFloat: 0,
        maxFloat: 0.85,
      },
    ],
  },
  {
    id: "the-revolution-collection",
    name: "The Revolution Collection",
    covert: [
      {
        baseName: "AK-47 | Head Shot",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "M4A4 | Temukau",
        minFloat: 0,
        maxFloat: 0.8,
      },
    ],
  },
  {
    id: "the-revolver-case-collection",
    name: "The Revolver Case Collection",
    covert: [
      {
        baseName: "M4A4 | Royal Paladin",
        minFloat: 0,
        maxFloat: 0.8,
      },
      {
        baseName: "R8 Revolver | Fade",
        minFloat: 0,
        maxFloat: 0.4,
      },
    ],
  },
  {
    id: "the-rising-sun-collection",
    name: "The Rising Sun Collection",
    covert: [
      {
        baseName: "AUG | Akihabara Accept",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-shadow-collection",
    name: "The Shadow Collection",
    covert: [
      {
        baseName: "M4A1-S | Golden Coil",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "USP-S | Kill Confirmed",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-shattered-web-collection",
    name: "The Shattered Web Collection",
    covert: [
      {
        baseName: "AWP | Containment Breach",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "MAC-10 | Stalker",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-snakebite-collection",
    name: "The Snakebite Collection",
    covert: [
      {
        baseName: "M4A4 | In Living Color",
        minFloat: 0,
        maxFloat: 0.79,
      },
      {
        baseName: "USP-S | The Traitor",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-spectrum-2-collection",
    name: "The Spectrum 2 Collection",
    covert: [
      {
        baseName: "AK-47 | The Empress",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "P250 | See Ya Later",
        minFloat: 0,
        maxFloat: 0.7,
      },
    ],
  },
  {
    id: "the-spectrum-collection",
    name: "The Spectrum Collection",
    covert: [
      {
        baseName: "AK-47 | Bloodsport",
        minFloat: 0,
        maxFloat: 0.45,
      },
      {
        baseName: "USP-S | Neo-Noir",
        minFloat: 0,
        maxFloat: 0.7,
      },
    ],
  },
  {
    id: "the-sport-field-collection",
    name: "The Sport & Field Collection",
    covert: [
      {
        baseName: "M4A1-S | Fade",
        minFloat: 0,
        maxFloat: 0.08,
      },
    ],
  },
  {
    id: "the-st-marc-collection",
    name: "The St. Marc Collection",
    covert: [
      {
        baseName: "AK-47 | Wild Lotus",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-train-2025-collection",
    name: "The Train 2025 Collection",
    covert: [
      {
        baseName: "AWP | LongDog",
        minFloat: 0,
        maxFloat: 1,
      },
    ],
  },
  {
    id: "the-vanguard-collection",
    name: "The Vanguard Collection",
    covert: [
      {
        baseName: "AK-47 | Wasteland Rebel",
        minFloat: 0.05,
        maxFloat: 0.7,
      },
      {
        baseName: "P2000 | Fire Elemental",
        minFloat: 0,
        maxFloat: 0.6,
      },
    ],
  },
  {
    id: "the-wildfire-collection",
    name: "The Wildfire Collection",
    covert: [
      {
        baseName: "AK-47 | Fuel Injector",
        minFloat: 0,
        maxFloat: 1,
      },
      {
        baseName: "M4A4 | The Battlestar",
        minFloat: 0,
        maxFloat: 0.64,
      },
    ],
  },
  {
    id: "the-winter-offensive-collection",
    name: "The Winter Offensive Collection",
    covert: [
      {
        baseName: "M4A4 | Asiimov",
        minFloat: 0.18,
        maxFloat: 1,
      },
      {
        baseName: "Sawed-Off | The Kraken",
        minFloat: 0,
        maxFloat: 0.4,
      },
    ],
  },
];

export const COLLECTIONS_WITH_FLOAT_MAP = new Map<
  string,
  CollectionFloatCatalogEntry
>();

export const COLLECTIONS_WITH_FLOAT_BY_NAME = new Map<
  string,
  CollectionFloatCatalogEntry
>();

export const COVERT_FLOAT_BY_BASENAME = new Map<string, CovertFloatRange>();

export const rebuildCollectionFloatCaches = (
  entries: CollectionFloatCatalogEntry[] = COLLECTIONS_WITH_FLOAT,
): void => {
  COLLECTIONS_WITH_FLOAT_MAP.clear();
  COLLECTIONS_WITH_FLOAT_BY_NAME.clear();
  COVERT_FLOAT_BY_BASENAME.clear();

  for (const entry of entries) {
    COLLECTIONS_WITH_FLOAT_MAP.set(entry.id, entry);
    COLLECTIONS_WITH_FLOAT_BY_NAME.set(entry.name.toLowerCase(), entry);
    for (const covert of entry.covert) {
      COVERT_FLOAT_BY_BASENAME.set(covert.baseName, covert);
    }
  }
};

rebuildCollectionFloatCaches();
